# Generated by Django 3.1.3 on 2021-01-25 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_recipe_time_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredientLine',
            field=models.ManyToManyField(to='core.IngredientLine'),
        ),
    ]
