# Generated by Django 3.1.3 on 2021-01-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_recipe_ingredientline'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
