# Generated by Django 3.1.3 on 2021-01-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210125_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='link',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredientLine',
            field=models.ManyToManyField(to='core.IngredientLine'),
        ),
    ]
