# Generated by Django 3.1.3 on 2021-01-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210125_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredientLine',
            field=models.ManyToManyField(blank=True, to='core.IngredientLine'),
        ),
    ]
