# Generated by Django 3.1.3 on 2021-01-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210125_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientline',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredientline',
            name='ingredient',
            field=models.ManyToManyField(blank=True, to='core.Ingredient'),
        ),
    ]
