# Generated by Django 3.1.3 on 2021-01-25 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210125_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredientLine',
        ),
        migrations.DeleteModel(
            name='IngredientLine',
        ),
    ]
