# Generated by Django 3.1.3 on 2021-01-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_recipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredientLine',
            field=models.ManyToManyField(blank=True, to='core.IngredientLine'),
        ),
    ]
