# Generated by Django 3.1.3 on 2021-01-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ingredientline_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredientLine',
            field=models.ManyToManyField(to='core.IngredientLine'),
        ),
    ]
