# Generated by Django 3.1.3 on 2021-01-25 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210125_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredientLine',
            new_name='ingredientLines',
        ),
    ]
