# Generated by Django 3.1.3 on 2021-01-25 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_ingredientline_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientline',
            name='ingredient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.ingredient'),
            preserve_default=False,
        ),
    ]
