# Generated by Django 3.1.3 on 2021-01-27 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_ingredientline_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
    ]
