# Generated by Django 3.1.3 on 2021-01-27 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_recipe_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredientLines',
        ),
        migrations.AddField(
            model_name='ingredientline',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientLines', to='core.recipe'),
            preserve_default=False,
        ),
    ]
