# Generated by Django 3.1.3 on 2021-01-28 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_ingredientline_measurement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
