# Generated by Django 3.1.5 on 2021-01-28 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientline',
            name='measurement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.measurement'),
            preserve_default=False,
        ),
    ]
