# Generated by Django 3.1.5 on 2021-03-09 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_ingredientline_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestParentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestChildTag',
            fields=[
                ('testparenttag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.testparenttag')),
                ('childLabel', models.CharField(max_length=255)),
            ],
            bases=('core.testparenttag',),
        ),
    ]
