# Generated by Django 3.1.5 on 2021-03-09 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_testchildtag_testparenttag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestChildWithUser',
            fields=[
                ('testparenttag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.testparenttag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.testparenttag',),
        ),
    ]
