# Generated by Django 3.1.5 on 2021-03-09 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0032_auto_20210309_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientline',
            name='recipe',
        ),
        migrations.AddField(
            model_name='ingredientline',
            name='content_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='ingredientline',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
