# Generated by Django 3.1.5 on 2021-03-09 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210309_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientline',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='ingredientline',
            name='object_id',
        ),
        migrations.AddField(
            model_name='ingredientline',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientLines', to='core.recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='core.Ingredient'),
        ),
        migrations.DeleteModel(
            name='GroceryList',
        ),
    ]
