# Generated by Django 3.1.5 on 2021-03-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20210309_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='core.Recipe'),
        ),
    ]
