# Generated by Django 3.1.5 on 2021-03-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_grocerylist_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='recipes',
            field=models.ManyToManyField(to='core.Recipe'),
        ),
    ]
